### ISSUE TITLE
docs missing

### ISSUE THREAD

**Issue by rmpinchback** [dmoggles/matplotlib_table#1]
The README for the project points to a docs/README.md for more information.  It's a dead link, it appears the docs either weren't checked in or not merged to the main branch.

**Comment by dmoggles** [comment]
This was unfortunately simply left over boilerplate code I didn't catch.  All the documentation that currently exists is contained in README.md. I've removed the comment from the file

https://github.com/dmoggles/matplotlib_table/pull/2
